---
env:
  DOCKER_IMAGE: gotosatoru/examplevotingapp_result:latest

name: Build & Scan result App
# template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/docker-build-scan-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/docker-build-scan-result.yaml'

jobs:
  build-push:
    name: Build
    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: true
      image-names: gotosatoru/examplevotingapp_result
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr
      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      context: result

      # platforms: linux/amd64,linux/arm64,linux/arm/v7
      platforms: linux/amd64

  sysdig-cli-scanner:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: build-push  # This ensures that the scan runs after the build job
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${DOCKER_IMAGE}

      - name: Install Sysdig CLI Scanner
        run: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          sudo mv sysdig-cli-scanner /usr/local/bin/sysdig-cli-scanner
          sudo chmod +x /usr/local/bin/sysdig-cli-scanner

      - name: Scan the Docker image
        env:
          SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
          SYSDIG_SECURE_ENDPOINT: https://app.au1.sysdig.com
        run: |
          /usr/local/bin/sysdig-cli-scanner --apiurl ${SYSDIG_SECURE_ENDPOINT} ${DOCKER_IMAGE}